spring.application.name=auth-service
server.port=8080

# Database — Person 3 will confirm the DB name and password

#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}

spring.datasource.url=jdbc:postgresql://ep-misty-pond-ao5t1m2f-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_3ZFXzhlcOLy1

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT secret key — share this exact value with Person 4
jwt.secret=gjhbsdghugdiughwrshgwersdhgiueghireuhiguhhhbyuebfhv